### PR TITLE
web: add option to use SignalR WS server from dotnet-api-starter

### PR DESCRIPTION
**Pull request by amonich**

### CODE REVIEW

**Review by yarmolovichalex — APPROVED** [review]

**Comment by yarmolovichalex** [comment]
Please add documentation on websocket server options and how to choose one [here](https://ship.paralect.com/docs/web/overview).

**Comment by Oigen43** [comment]
@amonich @yarmolovichalex 
Can we use create-ship-app to change socket.io to signalR when building .NET version instead commenting signalR and adding additional dependency?

**Comment by yarmolovichalex** [comment]
@Oigen43 I thought about that - it'd be ideal, but not trivial to implement. We can remove/rename files during build process (so two separate `package.json` files is a suboptimal possible solution). But in order to edit `package.json`, we need to introduce placeholders (or some other mechanism), and also make sure, that some value is set by default, so we can run ship as is. So I'd do this out of scope of this task. For now I'd comment out signalr service and dependency and describe in documentation, how to switch to it. cc @amonich

**Review by yarmolovichalex — APPROVED** [review]

**Comment by amonich** [comment]
@Oigen43, @yarmolovichalex 
I've added documentation on switching between socket.io and signalr.
It looks like these steps can be automated with create-ship-app , but maybe it's better to do this as a separate task

**Review by yarmolovichalex — APPROVED** [review]

**Review by Oigen43 — APPROVED** [review]

**Comment by Oigen43** [comment]
lgtm 👍

**Pull request merged**
