### PR TITLE
Fix api volume in docker-compose

### PR DESCRIPTION
**Pull request by hovoodd**

### CODE REVIEW

**Comment by ezhivitsa** [comment]
@hovoodd Please, make the same PR in the repository `paralect/koa-api-starter`.

**Comment by hovoodd** [comment]
@ezhivitsa that won't be necessary, everything appears fine there

**Comment by ezhivitsa** [comment]
@hovoodd No, we don't change files in the folders `api`, `react` and `landing` manually. We generate this folders automatically from repositories `paralect/koa-api-starter`, `paralect/koa-react-starter`, `paralect/nextjs-landing-starter`

**Comment by hovoodd** [comment]
@ezhivitsa very interesting, but we have correct file 

`docker-compose.yml` in `paralect/koa-api-starter`:
```
volumes:                                                                              
    - "./src:/app/src" 
```

**Pull request merged**
